# Generated by Django 2.1.15 on 2020-09-13 02:39

import custom_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVocabulary',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'document',
                    models.ForeignKey(
                        db_column='document_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='words_vector.Document',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'vocabulary',
                    custom_fields.ListField(blank=True, null=True, token=','),
                ),
                (
                    'documents',
                    models.ManyToManyField(
                        blank=True,
                        through='words_vector.DocumentVocabulary',
                        to='words_vector.Document',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='documentvocabulary',
            name='vocabulary',
            field=models.ForeignKey(
                db_column='vocabulary_id',
                on_delete=django.db.models.deletion.CASCADE,
                to='words_vector.Vocabulary',
            ),
        ),
    ]
