# Generated by Django 2.1.15 on 2020-09-14 00:21

import custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('files', custom_fields.ListField(token=',')),
                (
                    'vocabulary',
                    custom_fields.ListField(blank=True, null=True, token=','),
                ),
                ('vectors', custom_fields.ListField(blank=True, null=True, token=',')),
            ],
        )
    ]
